[versions]

version = "1.0.0"
group = "com.voinearadu"

[plugins]

loom = { id = "fabric-loom", version = "1.5.5" }

[libraries]

# Minecraft
minecraft_v20 = { module = "com.mojang:minecraft", version = "1.20.1" }

# Fabric
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version = "0.90.7+1.20.3" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version = "0.15.0" }
parchment_mappings = { module = "org.parchmentmc.data:parchment-1.20.1", version = "2023.09.03" }

# Velocioty
velocity = { module = "com.velocitypowered:velocity-api", version = "3.1.2-SNAPSHOT" }

# Dependencies
lombok = { module = "org.projectlombok:lombok", version = "1.18.30" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
reflections = { module = "org.reflections:reflections", version = "0.10.2" }
luckperms = { module = "net.luckperms:api", version = "5.4" }
kyori_minimessage = { module = "net.kyori:adventure-text-minimessage", version = "4.17.0" }
kyori_adventure_fabric = { module = "net.kyori:adventure-platform-fabric", version = "5.14.1" }
voinearadu_utils = { module = "com.voinearadu:utils", version = "1.0.1" }
